# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='dapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.DApp'),
        ),
    ]
