# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='confirmation_key',
            field=models.TextField(),
        ),
    ]
