# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170222_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Alert'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventvalue',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='events.Event'),
        ),
    ]
