# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170222_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='name',
        ),
    ]
