# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170223_1013'),
        ('events', '0005_remove_alert_name'),
    ]

    operations = [
    ]
